### ISSUE TITLE
Technical Milestones for the Nervos Grant

### ISSUE THREAD

**Issue by mwaa** [leapdao/meta#244]
# Bounty

## Scope
- Each milestone needs to have clear technical milestones i.e detailed design specs + level of code detail + a running instance of a module etc
- Planned call sessions with technical review team

## Deliverables

- Technical document shared with Nervos team

## Funding Circle
General Circle

## Bounty Owner/Gardener

@johannbarbie  as BizDev

## Gain for the Organization
Approved to proceed with Contract Signing

## Roles
bounty worker: @johannbarbie @mwaa 50% 50%
bounty reviewer: Nervos Technical 

## Gardener checklist

- [ ] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by mwaa** [comment]
Product: https://hackmd.io/@Nl-v0q6-QECFQD_SwX2dDA/Sk4BQVaTL
