### ISSUE TITLE
Draft: Leap Testnet launch

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#48]
- [x] [setup network nodes](https://github.com/leapdao/leap-node/issues/122) (> 2 nodes)
-  [setup contracts](https://github.com/leapdao/leap-contracts/issues/90)
   - [x] deploy properly named token on Rinkeby
   - [x] deploy plasma contracts (using the proper token, not MOCK)
   - [x] deploy governance contract and make it own plasma contracts
- [x] [setup bridge UI ](https://github.com/leapdao/bridge-ui/issues/85)
- [x] [set up LEAP token faucet](https://github.com/leapdao/leap-token-faucet/issues/5)
- [x] [define an executable set of integration tests](https://github.com/leapdao/leapdao-bounties/issues/26)
- [x] [set up monitoring](https://github.com/leapdao/leap-node/issues/123)
- [ ] [execute smoke tests](https://github.com/leapdao/leapdao-bounties/issues/49)
- [x] [create blog post](https://github.com/leapdao/leapdao-website/issues/16)

**Comment by johannbarbie** [comment]
closing, even thought smoke tests not done.
